import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        bg:                   "oklch(var(--color-bg-raw) / <alpha-value>)",
        surface:              "oklch(var(--color-surface-raw) / <alpha-value>)",
        "surface-elevated":   "oklch(var(--color-surface-elevated-raw) / <alpha-value>)",
        border:               "oklch(var(--color-border-raw) / <alpha-value>)",
        ink:                  "oklch(var(--color-ink-raw) / <alpha-value>)",
        muted:                "oklch(var(--color-muted-raw) / <alpha-value>)",
        primary:              "oklch(var(--color-primary-raw) / <alpha-value>)",
        "primary-hover":      "oklch(var(--color-primary-hover-raw) / <alpha-value>)",
        "primary-tint":       "oklch(var(--color-primary-tint-raw) / <alpha-value>)",
        "primary-tint-soft":  "oklch(var(--color-primary-tint-soft-raw) / <alpha-value>)",
        accent:               "oklch(var(--color-accent-raw) / <alpha-value>)",
        success:              "oklch(var(--color-success-raw) / <alpha-value>)",
        warning:              "oklch(var(--color-warning-raw) / <alpha-value>)",
        "warning-bright":     "oklch(var(--color-warning-bright-raw) / <alpha-value>)",
        "navy-deep":          "oklch(var(--color-navy-deep-raw) / <alpha-value>)",
        "navy-2":             "oklch(var(--color-navy-2-raw) / <alpha-value>)",
        "podium-gold":        "oklch(var(--color-podium-gold-raw) / <alpha-value>)",
        "podium-silver":      "oklch(var(--color-podium-silver-raw) / <alpha-value>)",
        "podium-bronze":      "oklch(var(--color-podium-bronze-raw) / <alpha-value>)",
        "award-fire":         "oklch(var(--color-award-fire-raw) / <alpha-value>)",
        "award-giant":        "oklch(var(--color-award-giant-raw) / <alpha-value>)",
        "award-android":      "oklch(var(--color-award-android-raw) / <alpha-value>)",
        "award-carry":        "oklch(var(--color-award-carry-raw) / <alpha-value>)",
        "award-duo":          "oklch(var(--color-award-duo-raw) / <alpha-value>)",
        error:                "oklch(var(--color-error-raw) / <alpha-value>)",
        "gender-m":           "oklch(var(--color-gender-m-raw) / <alpha-value>)",
        "gender-f":           "oklch(var(--color-gender-f-raw) / <alpha-value>)",
        "skill-advanced":       "oklch(var(--color-skill-advanced-raw) / <alpha-value>)",
        "skill-advanced-ink":   "oklch(var(--color-skill-advanced-ink-raw) / <alpha-value>)",
        "skill-intermediate":   "oklch(var(--color-skill-intermediate-raw) / <alpha-value>)",
        "skill-intermediate-ink":"oklch(var(--color-skill-intermediate-ink-raw) / <alpha-value>)",
        "skill-beginner":       "oklch(var(--color-skill-beginner-raw) / <alpha-value>)",
        "skill-beginner-ink":   "oklch(var(--color-skill-beginner-ink-raw) / <alpha-value>)",
        "skill-casual":         "oklch(var(--color-skill-casual-raw) / <alpha-value>)",
        "skill-casual-ink":     "oklch(var(--color-skill-casual-ink-raw) / <alpha-value>)",
      },
      fontFamily: {
        sans: ["var(--font-space-grotesk)", "system-ui", "sans-serif"],
        mono: ["var(--font-jetbrains-mono)", "ui-monospace", "monospace"],
        display: ["var(--font-barlow-condensed)", "Arial Narrow", "sans-serif"],
      },
      borderRadius: {
        sm:    "4px",
        DEFAULT: "8px",
        md:    "8px",
        lg:    "12px",
        pill:  "9999px",
      },
    },
  },
  plugins: [],
};
export default config;
